[package]
name = "splendor"
version = "0.1.0"
edition = "2021"

[lib]
name = "splendor"
crate-type = ["cdylib"]

[dependencies]
rand = "0.8"
rand_chacha = "0.3"
log = "0.4.27"
getset = "0.1.6"
once_cell = "1.19"
pyo3 = { version = "0.23", features = ["extension-module"] }
